name: Bug report (3.x)
description: Шаблон ошибок в Vue Yandex Maps 3.x
labels: ["bug", "3.x", "pending triage"]
assignees:
  - daniluk4000
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время указать нам на наши ошибки!
  - type: input
    id: version
    attributes:
      label: Версия библиотеки
      description: Пожалуйста, укажите версию библиотеки на момент написания этой формы
      placeholder: Например, 3.0.0
    validations:
      required: true
  - type: textarea
    id: how-to
    attributes:
      label: Как воспроизвести
      description: Опишите здесь шаги воспроизведения, приведите примеры кода, а еще лучше - укажите репозиторий, где можно воспроизвести проблему.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Опишите проблему
      description: Опишите простым и понятным языком, что идет не так, и какой результат ожидался
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Дополнительная информация
      description: Опишите, что еще нам нужно знать.
    validations:
      required: false
  - type: checkboxes
    id: validation
    attributes:
      label: Ответы на вопросы
      description: Пожалуйста, сверьтесь с пунктами ниже
      options:
        - label: Я использую версию 3.x
          required: true
        - label: Я поискал похожие ошибки и не нашел таковых
          required: true
