name: 'Codecheck'
description: 'Perform lint and build of project'

runs:
  using: composite
  steps:
    - name: Install deps
      shell: bash
      run: yarn
    - name: Lint
      shell: bash
      run: yarn lint
    - name: Build package
      shell: bash
      run: yarn build
    - name: Build docs
      shell: bash
      run: yarn docs:build
    - name: Test examples types
      shell: bash
      run: yarn workspace examples type-check
    - name: Build Nuxt
      shell: bash
      run: yarn workspace example-nuxt build
    - name: Generate Nuxt
      shell: bash
      run: yarn workspace example-nuxt generate
    - name: Generate Vue
      shell: bash
      run: yarn workspace example-vue build
